# Generated by Django 5.2.5 on 2025-09-13 15:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_subscribe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscribe",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "подписка",
                "verbose_name_plural": "подписки",
            },
        ),
        migrations.AlterUniqueTogether(
            name="subscribe",
            unique_together={("user", "course")},
        ),
        migrations.AddField(
            model_name="subscribe",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscribe",
            name="course",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="studies.course",
                verbose_name="курс",
            ),
        ),
        migrations.AlterField(
            model_name="subscribe",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterModelTable(
            name="subscribe",
            table="subscribes",
        ),
        migrations.RemoveField(
            model_name="subscribe",
            name="is_active",
        ),
    ]
